config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root "pages#index"

  namespace :api do
    post "/teacher/group/course", to: "teacher_group_courses#create"
    delete "/teacher/group/course", to: "teacher_group_courses#destroy"
  end

  resources :symbol
  resources :courses

  get "/groups/import", to: "imports#new"
  post "/groups/import", to: "imports#import"
  resources :groups

  resources :teachers do
    resources :reports, controller: "teacher_reports" do
      get "/email", to: "teacher_reports#email"
      post "/email", to: "teacher_reports#email_send"
    end
  end

  get "/documents/:filename", to: "documents#show"

  get "/settings", to: "settings#index"
  post "/settings", to: "settings#update"
  put "/settings", to: "settings#update"
  patch "/settings", to: "settings#update"

end

app/models/group.rb
class Group < ApplicationRecord
    # Definície vzťahov medzi modelmi
    has_many :group_courses, dependent: :destroy
    has_many :courses, through: :group_courses

    has_many :teacher_group_courses
    has_many :teachers, through: :teacher_group_courses

    default_scope { order(group_number: :asc) }

    # Validácie
    validates :group_number, presence: true, uniqueness: {case_sensitive: false}

    def teacher_group_courses?(teacher_id, course_id)
      tgc = TeacherGroupCourse.where('teacher_id = ? and group_id = ? and course_id = ?', teacher_id, self.id, course_id).first
      tgc.present?
    end

    # Funkcia na import z CSV súboru
    def self.import(file)
      CSV.foreach(file.path, row_sep: :auto, col_sep: ";") do |row|
        row.each do |column|
          if /\d{1}\w{2}[\w\d]{3}/.match(column)
            Group.create(group_number: column)
          end
        end
      end
    end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :find_group, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  def index
    @groups = Group.all
  end

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)

    if @group.save
      flash[:notice] = "Skupina #{@group.group_number} bola úspešne vytvorená"
      redirect_to groups_path
    else
      render 'new'
    end
  end

  def show
  end

  def edit
  end

  def update
    if @group.update_attributes(group_params)
      flash[:notice] = "Skupina #{@group.group_number} bola upravená"
      redirect_to groups_path
    else
      render :edit
    end
  end

  def destroy
    @group.destroy

    flash[:notice] = "Skupina #{@group.group_number} bola vymazaná"
    redirect_to groups_path
  end

  private
  def group_params
    params.require(:group).permit(:group_number, course_ids: [])
  end

  def find_group
    @group = Group.find(params[:id])
  end
end

app/views/groups/_form.html.erb
<%= form_for group do |f| %>
    <%= render 'layouts/errors', model: group %>

    <div class="form-group">
        <%= f.label "Číslo skupiny" %>
        <%= f.text_field :group_number, class: "form-control" %>
    </div>

    <h3>Predmety skupiny</h3>

    <div class="form-group">
        <%= f.collection_check_boxes(:course_ids, Course.all, :id, :name) do |b| %>
          <div class="checkbox">
            <%= b.label do %>
              <%= b.check_box(class: "checkbox") %>
              <%= b.object.name %>
            <% end %>
          </div>
        <% end %>
    </div>

    <div class="actions pull-right">
      <%= f.submit "Uložiť skupinu", class: "btn btn-primary" %>
    </div>
<% end %>

app/views/groups/edit.html.erb
<h1>Upraviť skupinu <%= @group.group_number %></h1>

<%= render 'form', group: @group %>

<%= link_to "Späť", groups_path %>

app/views/groups/index.html.erb
<header class="info-header">
  <h1>Skupiny</h1>
  <%= link_to "Pridať novú skupinu", new_group_path, class: 'btn btn-primary pull-right' %>
  <%= link_to "Importovať skupiny", groups_import_path, class: 'btn btn-success pull-right', style: 'margin-right: 1em' %>
</header>

<hr>

<% if @groups.size > 4 %>
  <% @left,@right = @groups.each_slice((@groups.size / 2.0).ceil).to_a %>
<% end %>

<% if @groups.size > 4 %>
<div class="double-table">
  <table class="table table-striped table-bordered">
    <thead>
      <tr>
        <th>Číslo skupiny</th>
        <th colspan="2" align="center">Akcie</th>
      </tr>
    </thead>

    <tbody>
      <% @left.each do |group| %>
        <tr>
          <td><%= group.group_number %></td>
          <td align="center">
            <%= link_to edit_group_path(group) do %>
              <span class="glyphicon glyphicon-pencil"></span> Upraviť
            <% end %>
          </td>
          <td align="center">
            <%= link_to group, method: :delete, data: { confirm: "Ste si istý?"} do %>
              <span class="glyphicon glyphicon-trash"></span> Vymazať
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <table class="table table-striped table-bordered">
    <thead>
      <tr>
        <th>Číslo skupiny</th>
        <th colspan="2" align="center">Akcie</th>
      </tr>
    </thead>

    <tbody>
    <% @right.each do |group| %>
      <tr>
        <td><%= group.group_number %></td>
        <td align="center">
          <%= link_to edit_group_path(group) do %>
            <span class="glyphicon glyphicon-pencil"></span> Upraviť
          <% end %>
        </td>
        <td align="center">
          <%= link_to group, method: :delete, data: { confirm: "Ste si istý?"} do %>
            <span class="glyphicon glyphicon-trash"></span> Vymazať
          <% end %>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>
<% else %>
  <table class="table table-striped table-bordered">
    <thead>
      <tr>
        <th>Číslo skupiny</th>
        <th colspan="2" align="center">Akcie</th>
      </tr>
    </thead>

    <tbody>
    <% @groups.each do |group| %>
      <tr>
        <td><%= group.group_number %></td>
        <td align="center">
          <%= link_to edit_group_path(group) do %>
            <span class="glyphicon glyphicon-pencil"></span> Upraviť
          <% end %>
        </td>
        <td align="center">
          <%= link_to group, method: :delete, data: { confirm: "Ste si istý?"} do %>
            <span class="glyphicon glyphicon-trash"></span> Vymazať
          <% end %>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
<% end %>

app/views/groups/new.html.erb
<h1>Nová skupina</h1>

<%= render 'form', group: @group %>

<%= link_to "Späť", groups_path %>

app/views/groups/show.html.erb
<h1>Courses#show</h1>
<p>Find me in app/views/courses/show.html.erb</p>