config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root "pages#index"

  namespace :api do
    post "/teacher/group/course", to: "teacher_group_courses#create"
    delete "/teacher/group/course", to: "teacher_group_courses#destroy"
  end

  resources :symbol
  resources :courses

  get "/groups/import", to: "imports#new"
  post "/groups/import", to: "imports#import"
  resources :groups

  resources :teachers do
    resources :reports, controller: "teacher_reports" do
      get "/email", to: "teacher_reports#email"
      post "/email", to: "teacher_reports#email_send"
    end
  end

  get "/documents/:filename", to: "documents#show"

  get "/settings", to: "settings#index"
  post "/settings", to: "settings#update"
  put "/settings", to: "settings#update"
  patch "/settings", to: "settings#update"

end

app/models/teacher.rb
class Teacher < ApplicationRecord
  has_many :teacher_courses
  has_many :courses, through: :teacher_courses

  has_many :teacher_group_courses
  has_many :groups, through: :teacher_group_courses

  has_many :documents

  validates :name, presence: true
  validates :email, presence: true

  def lecturer_ids
    ids = self.teacher_courses.select{ |c| c.is_lecturer }.map{|i| i.course_id}
  end

  def total(course)
    t = 0
    lecture = Multiplier.find_by(name: 'Prednáška').value
    classes = Multiplier.find_by(name: 'Cvičenie').value
    labs = Multiplier.find_by(name: 'Laboratórne cvičenie').value
    weeks = 13

    self.teacher_courses.each do |tc|
      if tc.course.id == course.id
        if tc.is_lecturer
          t += tc.course.lectures_weekly * lecture * weeks
        end

        tc.course.groups.each do |group|
          if group.teacher_group_courses?(self.id, tc.course_id)
            t += tc.course.classes_weekly * classes * weeks
            t += tc.course.lab_classes_weekly * labs * weeks
          end
        end
      end
    end

    t
  end

  # Migration
  # t.string :name
  # t.string :email
  # t.timestamps
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  before_action :find_teacher, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  helper_method :sort_column, :sort_direction

  # Prehľad vyučujúcich
  def index
    @teachers = Teacher.order(sort_column + " " + sort_direction).all
  end

  # Formulár nového vyučujúceho
  def new
    @teacher = Teacher.new
    @tgc = @teacher.teacher_group_courses
  end

  # Vytvorenie nového vyučujúceho
  def create
    @teacher = Teacher.new(teacher_params)

    if @teacher.save
      update_lecturer_status()
      flash[:notice] = "Vyučujúci #{@teacher.name} bol úspešne vytvorený"
      redirect_to edit_teacher_path(@teacher)
    else
      render 'new'
    end
  end

  # Prehľad vyučujúceho
  def show
    @total = 0
    multipliers = Multiplier.all()
    @lecture = multipliers.find { |el| el.name == 'Prednáška'}.value
    @classes = multipliers.find { |el| el.name == 'Cvičenie'}.value
    @labs = multipliers.find { |el| el.name == 'Laboratórne cvičenie'}.value
    @weeks = 13

    @teacher.teacher_courses.each do |tc|
      if tc.is_lecturer
        @total += tc.course.lectures_weekly * @lecture * @weeks
      end

      tc.course.groups.each do |group|
        # if group.teacher_group_courses?(@teacher.id, tc.course_id)
        if @teacher.teacher_group_courses.any? { |el| el.group_id == group.id && el.course_id == tc.course_id }
          @total += tc.course.classes_weekly * @classes * @weeks
          @total += tc.course.lab_classes_weekly * @labs * @weeks
        end
      end
    end
  end

  # Formulár úpravy vyučujúceho
  def edit
    @tgc = @teacher.teacher_group_courses
  end

  # Úprava vyučujúceho
  def update
    if @teacher.update_attributes(teacher_params)
      update_lecturer_status()
      update_teacher_group_courses()
      generate_pdf()
      flash[:notice] = "Vyučujúci #{@teacher.name} bol upravený"
      redirect_to edit_teacher_path(@teacher)
    else
      render :edit
    end
  end

  # Odstránenie vyučujúceho
  def destroy
    @teacher.destroy

    flash[:notice] = "Vyučujúci #{@teacher.name} bol vymazaný"
    redirect_to teachers_path
  end

  private
  def teacher_params
    params.require(:teacher).permit(:name, :email, :lecturer_ids, {course_ids: []}, {teacher_group_course_ids: []})
  end

  def find_teacher
    @teacher = Teacher.includes(:teacher_group_courses, teacher_courses: [{course: :groups}]).find(params[:id])
    # @teacher = Teacher.find(params[:id])
  end

  def sort_column
    Teacher.column_names.include?(params[:sort]) ? params[:sort] : 'name'
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end

  def generate_pdf
    filename = "#{@teacher.name.parameterize}-uvazky-#{Date.today}.pdf"
    doc = Document.find_by(filename: filename)

    if !doc.present?
      doc = Document.create(filename: filename, status: 'Generuje sa')
      @teacher.documents << doc
    else
      doc.update_attribute(:status, 'Generuje sa')
    end

    Delayed::Job.enqueue ::GeneratePdfJob.new(doc.id)
  end

  # Priradenie prednášajúcich predmetov
  def update_lecturer_status
    ids = params[:teacher][:lecturer_ids]

    if ids.present?
      ids.map!(&:to_i)
      @teacher.teacher_courses.each do |course|
        course.is_lecturer = if ids.include?(course.course_id)
          true
        else
          false
        end

        course.save()
      end
    else
      @teacher.teacher_courses.each do |course|
        course.is_lecturer = false
        course.save
      end
    end
  end

  def update_teacher_group_courses
    @teacher.teacher_group_courses.each do |tgc|
      if !@teacher.course_ids.include?(tgc.course_id)
        tgc.destroy
      end
    end
  end

  # t.string :personal_number
  # t.string :name
  # t.boolean :is_lecturer, default: false
end

app/helpers/api/teachers_helper.rb
module Api::TeachersHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/teachers/_form.html.erb
<%= form_for teacher do |f| %>
    <%= render 'layouts/errors', model: teacher %>

    <div class="form-group">
        <%= f.label "Meno a priezvisko" %>
        <%= f.text_field :name, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label "Email" %>
      <%= f.text_field :email, class: "form-control" %>
    </div>

    <div class="form-group">
      <h3>Vyučované predmety</h3>
      <table class="table table-striped table-bordered">
        <thead>
        <td colspan="2">Predmet</td>
        <td align="center">Je prednášajúci</td>
        </thead>
        <%= f.collection_check_boxes(:course_ids, Course.all, :id, :name) do |c| %>
            <tr>
              <td align="center" class="course--checkbox">
                <%= c.check_box(class: "checkbox") %>
              </td>
              <td class="course--checkbox">
                <div><%= c.label %></div>
                <% if @teacher.courses.include?(c.object) %>
                  <div class="course__wrap">
                  <div style="padding-right: 1em;">Skupiny:</div>
                  <div class="course__groups">
                    <% c.object.groups.each do |g| %>
                      <% if teacher.teacher_group_courses.any? { |el| el.group_id == g.id && el.course_id == c.object.id } %>
                      <label class="tgc__label"><input type="checkbox" name="teacher[tgc]" class="teacher-course-group" value="<%= g.id %>" data-course="<%= c.object.id %>" data-group="<%= g.id %>" data-teacher="<%= teacher.id %>" checked> <%= g.group_number %> </label>
                      <% else %>
                      <label class="tgc__label"><input type="checkbox" name="teacher[tgc]" class="teacher-course-group" value="<%= g.id %>" data-course="<%= c.object.id %>" data-group="<%= g.id %>" data-teacher="<%= teacher.id %>"> <%= g.group_number %> </label>
                      <% end %>
                    <% end %>
                  </div>
                  </div>
                <% end %>
              </td>
              <td align="center" class="course--checkbox">
                <%= check_box_tag "teacher[lecturer_ids][]", c.object.id, teacher.lecturer_ids.include?(c.object.id) %>
              </td>
            </tr>
        <% end %>
      </table>
    </div>

    <div class="actions form-group pull-right">
      <%= link_to "Zobraziť aktuálnu zostavu", teacher, class: "btn btn-default" %>
      <%= f.submit "Uložiť vyučujúceho", class: "btn btn-primary" %>
    </div>
<% end %>

app/views/teachers/_teacher.html.erb
<h2>Prehľad úväzkov vyučujúceho</h2>

<hr>
<h3 style="margin-bottom: 1em"><%= teacher.name %></h3>

<h4 style="font-weight: 400; margin-bottom: 1em">Prehľad vyučovaných hodín za semester</h4>

<table class="table table-bordered compact">
  <thead>
  <tr>
    <td colspan="2">Predmet</td>
    <td align="right">Trvanie (v hodinách)</td>
    <td align="right">Hodín za semester</td>
    <td align="right">Ohodnotenie</td>
  </tr>
  </thead>

  <tbody>
  <% teacher.teacher_courses.each do |tc| %>
    <% if tc.is_lecturer %>
      <tr>
        <td><%= tc.course.name %></td>
        <td>P</td>
        <td align="right"><%= tc.course.lectures_weekly %></td>
        <td align="right"><%= tc.course.lectures_weekly * weeks %></td>
        <td align="right"><%= tc.course.lectures_weekly * lecture * weeks %></td>
      </tr>
    <% end %>

    <% tc.course.groups.each do |group| %>
      <% if teacher.teacher_group_courses.any? { |el| el.group_id == group.id && el.course_id == tc.course_id } %>
        <% if tc.course.classes_weekly > 0 %>
          <tr>
            <td><%= tc.course.name %></td>
            <td>C - <%= group.group_number %></td>
            <td align="right"><%= tc.course.classes_weekly %></td>
            <td align="right"><%= tc.course.classes_weekly * weeks %></td>
            <td align="right"><%= tc.course.classes_weekly * classes * weeks %></td>
          </tr>
        <% end %>

        <% if tc.course.lab_classes_weekly > 0 %>
          <tr>
            <td><%= tc.course.name %></td>
            <td>L - <%= group.group_number %></td>
            <td align="right"><%= tc.course.lab_classes_weekly %></td>
            <td align="right"><%= tc.course.lab_classes_weekly * weeks %></td>
            <td align="right"><%= tc.course.lab_classes_weekly * labs * weeks %></td>
          </tr>
        <% end %>
      <% end %>
    <% end %>
  <% end %>
  </tbody>

  <tfoot style="border-top: 2px solid #ddd">
  <tr>
    <td colspan="4" align="right"><strong>Spolu:</strong></td>
    <td align="right"><%= total %></td>
  </tr>
  </tfoot>
</table>

app/views/teachers/edit.html.erb
<h1>Upraviť vyučujúceho <%= @teacher.name %></h1>
<hr>

<%= render 'form', teacher: @teacher %>

<%= link_to "Späť", teachers_path %>

app/views/teachers/index.html.erb
<header class="info-header">
  <h1>Vyučujúci</h1>
  <%= link_to "Pridať vyučujúceho", new_teacher_path, class: 'btn btn-primary pull-right' %>
</header>
<hr>

<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th><%= sortable("name", "Meno") %></th>
      <th><%= sortable("email") %></th>
      <th colspan="4" align="center">Akcie</th>
    </tr>
  </thead>

  <tbody>
    <% @teachers.each do |teacher| %>
      <tr>
        <td><%= teacher.name %></td>
        <td><%= teacher.email %></td>
        <td align="center">
          <%= link_to teacher do %>
            <span class="glyphicon glyphicon-search"></span> Prehľad
          <% end %>
        </td>
        <td align="center">
          <%= link_to teacher_reports_path(teacher) do %>
            <span class="glyphicon glyphicon-folder-open"></span> Generované dokumenty
          <% end %>
        </td>
        <td align="center">
          <%= link_to edit_teacher_path(teacher) do %>
            <span class="glyphicon glyphicon-pencil"></span> Upraviť
          <% end %>
        </td>
        <td align="center">
          <%= link_to teacher, method: :delete, data: { confirm: "Ste si istý?"} do %>
            <span class="glyphicon glyphicon-trash"></span> Vymazať
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/teachers/new.html.erb
<h1>Nový vyučujúci</h1>

<%= render 'form', teacher: @teacher %>

<%= link_to "Späť", teachers_path %>

app/views/teachers/show.html.erb
<%= link_to "← Všetci vyučujúci", teachers_url %>

<%= render 'teacher', teacher: @teacher, total: @total, lecture: @lecture, classes: @classes, labs: @labs, weeks: @weeks %>