config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root "pages#index"

  namespace :api do
    post "/teacher/group/course", to: "teacher_group_courses#create"
    delete "/teacher/group/course", to: "teacher_group_courses#destroy"
  end

  resources :symbol
  resources :courses

  get "/groups/import", to: "imports#new"
  post "/groups/import", to: "imports#import"
  resources :groups

  resources :teachers do
    resources :reports, controller: "teacher_reports" do
      get "/email", to: "teacher_reports#email"
      post "/email", to: "teacher_reports#email_send"
    end
  end

  get "/documents/:filename", to: "documents#show"

  get "/settings", to: "settings#index"
  post "/settings", to: "settings#update"
  put "/settings", to: "settings#update"
  patch "/settings", to: "settings#update"

end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :find_course, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # Prehľad predmetov
  def index
    @courses = Course.all
  end

  # Formulár nového predmetu
  def new
    @course = Course.new
  end

  # Vytvorenie nového predmetu
  def create
    @course = Course.new(course_params)

    if @course.save
      flash[:notice] = "Predmet #{@course.name} bol úspešne vytvorený"
      redirect_to courses_path
    else
      render 'new'
    end
  end

  # Prehľad predmetu
  def show
    multipliers = Multiplier.all()
    @lecture = multipliers.find { |el| el.name == 'Prednáška'}.value
    @classes = multipliers.find { |el| el.name == 'Cvičenie'}.value
    @labs = multipliers.find { |el| el.name == 'Laboratórne cvičenie'}.value
    @weeks = 13
  end

  # Formulár úpravy predmetu
  def edit
  end

  # Úprava predmetu
  def update
    if @course.update_attributes(course_params)
      flash[:notice] = "Predmet #{@course.name} bol upravený"
      redirect_to courses_path
    else
      render :edit
    end
  end

  # Zmazanie predmetu
  def destroy
    @course.destroy

    flash[:notice] = "Predmet #{@course.name} bol vymazaný"
    redirect_to courses_path
  end

  private
  # Whitlisting parametrov z requestu
  def course_params
    params.require(:course).permit(:code, :name, :lectures_weekly, :classes_weekly, :lab_classes_weekly)
  end

  # Nájdenie predmetu
  def find_course
    @course = Course.find(params[:id])
  end

  # Migrácia:
  # t.string :code, null: false
  # t.integer :lectures_weekly
  # t.integer :classes_weekly
  # t.integer :lab_classes_weekly
end

app/helpers/api/courses_helper.rb
module Api::CoursesHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/courses/_form.html.erb
<%= form_for course do |f| %>
    <%= render 'layouts/errors', model: course %>

    <div class="form-group">
        <%= f.label "Kód predmetu" %>
        <%= f.text_field :code, class: "form-control" %>
    </div>

    <div class="form-group">
        <%= f.label "Meno predmetu" %>
        <%= f.text_field :name, class: "form-control" %>
    </div>

    <div class="row form-group">
        <div class="col-xs-4">
          <%= f.label "Prednášky týždenne" %>
          <%= f.number_field :lectures_weekly, class: "form-control" %>
        </div>

        <div class="col-xs-4">
          <%= f.label "Cvičenia týždenne" %>
          <%= f.number_field :classes_weekly, class: "form-control" %>
        </div>

        <div class="col-xs-4">
          <%= f.label "Laboratórne cvičenia týždenne" %>
          <%= f.number_field :lab_classes_weekly, class: "form-control" %>
        </div>
    </div>

    <div class="actions form-group pull-right">
      <%= f.submit "Uložiť predmet", class: "btn btn-primary" %>
    </div>
<% end %>

app/views/courses/edit.html.erb
<h1>Upraviť predmet <%= @course.name %></h1>

<%= render 'form', course: @course %>

<%= link_to "Späť", courses_path %>

app/views/courses/index.html.erb
<header class="info-header">
  <h1>Predmety</h1>
  <%= link_to "Pridať predmet", new_course_path, class: 'btn btn-primary pull-right' %>
</header>

<hr>

<table class="table table-striped table-bordered">
  <thead>
    <tr>
      <td rowspan="2" class="tdmiddle">Kód</td>
      <td rowspan="2" style="vertical-align: middle">Meno</td>
      <td colspan="3" align="center">Hodín týždenne</td>
      <td colspan="3" rowspan="2" align="center">Akcie</td>
    </tr>
    <tr>
      <td align="right">Prednášky</td>
      <td align="right">Cvičenia</td>
      <td align="right">Lab. cvičenia</td>
    </tr>
  </thead>

  <tbody>
    <% @courses.each do |course| %>
      <tr>
        <td><%= course.code %></td>
        <td><%= course.name %></td>
        <td align="right"><%= course.lectures_weekly %></td>
        <td align="right"><%= course.classes_weekly %></td>
        <td align="right"><%= course.lab_classes_weekly %></td>
        <td align="center">
          <%= link_to course_path(course) do %>
            <span class="glyphicon glyphicon-search"></span> Prehľad
          <% end %>
        </td>
        <td align="center">
          <%= link_to edit_course_path(course) do %>
            <span class="glyphicon glyphicon-pencil"></span> Upraviť
          <% end %>
        </td>
        <td align="center">
          <%= link_to course, method: :delete, data: { confirm: "Ste si istý?"} do %>
            <span class="glyphicon glyphicon-trash"></span> Vymazať
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/courses/new.html.erb
<h1>Nový predmet</h1>

<%= render 'form', course: @course %>

<%= link_to "Späť", courses_path %>

app/views/courses/show.html.erb
<h1>Prehľad úväzkov vyučujúcich predmetu <%= @course.name %></h1>

<hr>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>Vyučujúci</th>
      <th>Úväzky</th>
      <th style="text-align: right;">Hodnota úväzku pre daný predmet</th>
    </tr>
  </thead>
  <tbody>
    <% @course.teachers.each do |teacher| %>
        <tr>
            <td style="vertical-align: middle"><%= teacher.name %></td>
            <td>
              <% teacher.teacher_courses.each do |tc| %>
              <% if tc.course.id == @course.id %>
                <% if tc.is_lecturer %>
                  <div class="uvazok">
                  Prednášky
                  </div>
                <% end %>

                <% tc.course.groups.each do |group| %>
                  <% if teacher.teacher_group_courses.any? { |el| el.group_id == group.id && el.course_id == tc.course_id } %>
                    <% if tc.course.classes_weekly > 0 %>
                      <div class="uvazok">
                      C - <%= group.group_number %>
                      </div>
                    <% end %>

                    <% if tc.course.lab_classes_weekly > 0 %>
                      <div class="uvazok">
                      L - <%= group.group_number %>
                      </div>
                    <% end %>
                  <% end %>
                <% end %>
              <% end %>
              <% end %>
            </td>
          <td align="right" style="vertical-align: middle"><%= teacher.total(@course) %></td>
        </tr>
      <% end %>
  </tbody>
</table>