config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root "pages#index"

  namespace :api do
    post "/teacher/group/course", to: "teacher_group_courses#create"
    delete "/teacher/group/course", to: "teacher_group_courses#destroy"
  end

  resources :symbol
  resources :courses

  get "/groups/import", to: "imports#new"
  post "/groups/import", to: "imports#import"
  resources :groups

  resources :teachers do
    resources :reports, controller: "teacher_reports" do
      get "/email", to: "teacher_reports#email"
      post "/email", to: "teacher_reports#email_send"
    end
  end

  get "/documents/:filename", to: "documents#show"

  get "/settings", to: "settings#index"
  post "/settings", to: "settings#update"
  put "/settings", to: "settings#update"
  patch "/settings", to: "settings#update"

end

app/controllers/teacher_reports_controller.rb
class TeacherReportsController < ApplicationController
  before_action :authenticate_user!

  def index
    @teacher = Teacher.includes(:documents).find(params[:teacher_id])
  end

  def show
    @document = Document.find(params[:id])

    file = Rails.root.join("pdfs", @document.filename)

    send_file(file, filename: @document.filename, type: "application/pdf", disposition: 'inline')
  end

  #### Koeficienty
  @@lecture = 4.0
  @@classes = 2.0

  def create
    @teacher = Teacher.find(params[:teacher_id])
    filename = "#{@teacher.name.parameterize}-uvazky-#{Date.today}.pdf"

    @total = 0

    @teacher.teacher_courses.each do |tc|
      if tc.is_lecturer
        @total += tc.course.lectures_weekly * @@lecture
      end

      tc.course.groups.each do |group|
        if group.teacher_group_courses?(@teacher.id, tc.course_id)
          @total += tc.course.classes_weekly * @@classes
          @total += tc.course.lab_classes_weekly * @@classes
        end
      end
    end

    if (! Document.find_by(filename: filename).present?)
      @teacher.documents << Document.create(filename: filename)
    end

    render pdf: filename,
           layout: 'pdf',
           template: 'teachers/show',
           encoding: 'utf-8',
           save_to_file: Rails.root.join('pdfs', filename)
  end

  def email
    @teacher = Teacher.find(params[:teacher_id])
    @document = Document.find(params[:report_id])
  end

  def email_send
    @teacher = Teacher.find(params[:teacher_id])
    @document = Document.find(params[:report_id])
    @body = params[:body]
    @subject = params[:subject]

    ReportMailer.mail_teacher_report(@teacher, @document, @subject, @body).deliver_later

    @document.sent_count += 1
    @document.save

    flash[:notice] = "Email bol úspešne odoslaný"

    redirect_to teacher_reports_path
  end

  def destroy
    @document = Document.find(params[:id])

    @document.destroy!

    redirect_to teacher_reports_path
  end
end

app/helpers/teacher_reports_helper.rb
module TeacherReportsHelper
end

app/views/teacher_reports/email.html.erb
<h1>Odoslať prehľad úväzku emailom</h1>

<h4>
  <strong>Príjemca:</strong>
  <span style="font-weight: 400"><%= @teacher.name %> <%= '<' %><%= @teacher.email %><%= '>' %></span>
</h4>

<hr>

<%= form_tag teacher_report_email_url do %>
    <div class="form-group">
        <%= label_tag :subject, "Predmet emailu" %>
        <%= text_field_tag :subject, "", {class: "form-control"} %>
    </div>

    <div class="form-group">
      <%= label_tag :body, "Text emailu" %>
      <%= text_area_tag :body, "", {class: "form-control"} %>
    </div>

    <div class="form-group">
      Príloha: <%= link_to @document.filename, teacher_report_path(@teacher.id, @document.id), target: "_blank" %>
    </div>

    <div class="form-group">

      <%= submit_tag "Odoslať prehľad úväzku na #{@teacher.email}", class: "btn btn-primary pull-right" %>
    </div>
<% end %>

app/views/teacher_reports/index.html.erb
<%= link_to "← Všetci vyučujúci", teachers_url %>

<h2>Dokumenty - <span style="font-weight: 400"><%= @teacher.name %></span></h2>

<hr>

<table class="table table-bordered table-striped">
  <thead>
    <td>Názov</td>
    <td>Dátum vytvorenia</td>
    <td>Stav</td>
    <td>Odoslané e-mailom</td>
    <td colspan="3" align="center">Akcie</td>
  </thead>

  <tbody>
  <% @teacher.documents.each do |doc| %>
      <tr>
        <td><%= doc.filename %></td>
        <td><%= doc.created_at.strftime("%d.%m.%Y") %></td>
        <td><%= doc.status %></td>
        <td>
          <% if doc.sent_count <= 0 %>
            Nie
          <% else %>
            Áno (<%= doc.sent_count %>x)
          <% end %>
        </td>
        <td align="center">
          <%= link_to teacher_report_url(@teacher.id, doc.id), target: "_blank" do %>
            <span class="glyphicon glyphicon-search"></span> Zobraziť
          <% end %>
        </td>
        <td align="center">
          <%= link_to teacher_report_email_url(@teacher.id, doc.id) do %>
            <span class="glyphicon glyphicon-envelope"></span> Odoslať e-mailom
          <% end %>
        </td>
        <td align="center">
          <%= link_to teacher_report_url(@teacher.id, doc.id), method: :delete do %>
            <span class="glyphicon glyphicon-trash"></span> Vymazať
          <% end %>
        </td>
      </tr>
  <% end %>
  </tbody>
</table>